controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

hello_world_index:
    path: /hello_world
    controller: App\Controller\HelloWorldController::__invoke