controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::__invoke

hello_world_index:
    path: /hello_world
    controller: App\Controller\HelloWorldController::__invoke

products:
    resource: './routes/custom/products.yaml'
    prefix: /products
    name_prefix: products_